### ISSUE TITLE
Cant install pycocotools 

### ISSUE THREAD

**Issue by Eldiablozzz** [Tps-F/sd-webui-blip2#10]
Hi i tried installing this on automatic1111, but lavis could not be installed due to failure in pycocotools installation. error is as follows.

Building wheel for pycocotools (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pycocotools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\pycocotools
      copying pycocotools\coco.py -> build\lib.win-amd64-cpython-310\pycocotools
      copying pycocotools\cocoeval.py -> build\lib.win-amd64-cpython-310\pycocotools
      copying pycocotools\mask.py -> build\lib.win-amd64-cpython-310\pycocotools
      copying pycocotools\__init__.py -> build\lib.win-amd64-cpython-310\pycocotools
      running build_ext
      cythoning pycocotools/_mask.pyx to pycocotools\_mask.c
      C:\Users\Office PC\AppData\Local\Temp\pip-build-env-33xdxvhq\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\Office PC\AppData\Local\Temp\pip-install-b89_0me7\pycocotools_8a34d91df0aa4dddb120d85857272ba3\pycocotools\_mask.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      building 'pycocotools._mask' extension
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\common
      creating build\temp.win-amd64-cpython-310\Release\pycocotools
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IC:\Users\Office PC\AppData\Local\Temp\pip-build-env-33xdxvhq\overlay\Lib\site-packages\numpy\core\include" -I./common -ID:\SD1\stable-diffusion-webui\venv\include -ID:\Users\OfficePC1\AppData\Local\Programs\Python\Python310\include -ID:\Users\OfficePC1\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /Tc./common/maskApi.c /Fobuild\temp.win-amd64-cpython-310\Release\./common/maskApi.obj
      maskApi.c
      ./common/maskApi.c(8): fatal error C1083: Cannot open include file: 'math.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
Failed to build pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects

i installed buildtools again but still error persists.

**Comment by Tps-F** [comment]
Does this directory exist?
`C:\Program Files (x86)\Windows Kits\10\Include\<YOURVIRSION>\ucrt`

**Comment by Eldiablozzz** [comment]
Nope in Windows Kits\10  folder there is no folder named include

**Comment by Tps-F** [comment]
Okay-
Plase open Visual Studio Installer >  Modify > Check Desktop development with C++ and install

**Comment by Eldiablozzz** [comment]
Thanks i will check it out again

**Comment by Tps-F** [comment]
There shouldn't be.
If you can't, try download from https://developer.microsoft.com/ja-jp/windows/downloads/windows-sdk/

**Comment by Eldiablozzz** [comment]
Windows 11 SDK was required. Now it has installed. Thanks.
