### ISSUE TITLE
VRAM not freed when unloading model.

### ISSUE THREAD

**Issue by Subcode** [Tps-F/sd-webui-blip2#11]
**Describe the bug**
The unload model button does not seem to work even though console reports, unloading model, finish!
VRAM is still used and thus model is not unloaded.

**To Reproduce**
1. Load the model
2. Check VRAM usage
3. Unload model
4. See VRAM still used

**Expected behavior**
VRAM should be freed when the model is unloaded

![image](https://user-images.githubusercontent.com/661544/231209023-171e7c13-78fa-4759-a6be-e26c718a5a5b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by Tps-F** [comment]
I'll fix it as soon as school is out today.

**Comment by Tps-F** [comment]
Thank you!
