### ISSUE TITLE
Suggestion:  add the ability to process a directory of images

### ISSUE THREAD

**Issue by gessyoo** [Tps-F/sd-webui-blip2#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tps-F** [comment]
Great idea!
And while we're at it, something to manage the images might be useful.
I'll give it a try!

**Comment by LexCybermac** [comment]
very interested in a batch process feature also

**Comment by Tps-F** [comment]
Sounds good!
I'll do after finish exams!

**Comment by Tps-F** [comment]
I'm finish it-
f60e74a
