### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 25 but got size 5 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by AhBumm** [Tps-F/sd-webui-blip2#23]
**Describe the bug**
all models can't work with the error logs :
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 25 but got size 5 for tensor number 1 in the list.

**Screenshots**
![屏幕截图 2023-09-05 095013](https://github.com/Tps-F/sd-webui-blip2/assets/103174943/98eeb0b6-877d-48d8-9125-956f382b702d)

**Desktop (please complete the following information):**
 - Device: 4090 with torch2.0.1&cu117
 - OS: windows11
 - Browser: chrome
 - Version: latest

**Comment by oaefou** [comment]
![ice_screenshot_20230905-185643](https://github.com/Tps-F/sd-webui-blip2/assets/126910733/a04892fc-042c-49d4-9c00-8e087c6b3b7d)
win10 rtx 3090 similar issue

**Comment by oaefou** [comment]
Version: 1.6.0 has a bug.
Version: 1.4.1 everything works fine.

**Comment by oaefou** [comment]
Version: ## 1.4.1  stable-diffusion-webui-master.zip

You need to install the previous version! Everything works in it.

[stable-diffusion-webui-master.zip](https://github.com/Tps-F/sd-webui-blip2/files/12526254/stable-diffusion-webui-master.zip)

**Comment by Balladie** [comment]
I temporarily fixed it by reinstalling LAVIS from source.
Seems PyPI version of LAVIS v1.0.2 have compatibility problem with transformers v4.30.2 which is required from latest version of WebUI. 

```bash
pip uninstall salesforce-lavis
pip install git+https://github.com/salesforce/LAVIS.git
```

**Comment by Tps-F** [comment]
I'll test

**Comment by AhBumm** [comment]
> I temporarily fixed it by reinstalling LAVIS from source. Seems PyPI version of LAVIS v1.0.2 have compatibility problem with transformers v4.30.2 which is required from latest version of WebUI.
> 
> ```shell
> pip uninstall salesforce-lavis
> pip install git+https://github.com/salesforce/LAVIS.git
> ```

Thanks,it works.
