### ISSUE TITLE
batch process feature

### ISSUE THREAD

**Issue by Tps-F** [Tps-F/sd-webui-blip2#3]
very interested in a batch process feature also

_Originally posted by @LexCybermac in https://github.com/Tps-F/sd-webui-blip2/issues/2#issuecomment-1452721299_

**Comment by oaefou** [comment]
I second that! Really need this feature

**Comment by goblin776655** [comment]
We all need it!!!
Plz help as!!!

**Comment by Tps-F** [comment]
Can you be a little more specific?
Looks interesting

**Comment by goblin776655** [comment]
> Can you be a little more specific? Looks interesting

Look at Train menu at 1111 
Than at Preprocess images - Use BLIP for caption checkbox.
If you add Use BLIP2 for caption - will be super! )

**Comment by oaefou** [comment]
![ice_screenshot_20230304-154649](https://user-images.githubusercontent.com/126910733/222902203-a53ef1b7-d9c3-4445-a0fe-751d3624943f.jpeg)

**Comment by Tps-F** [comment]
Thanks guys!!!
I'll get to it as soon as the school exams are done.

**Comment by oaefou** [comment]
https://github.com/p1atdev/stable-diffusion-webui-blip2-captioner

**Comment by Tps-F** [comment]
I'm finish it-
f60e74a

**Comment by Tps-F** [comment]
Oops
I'll fix it as soon as I eat.

> Make it possible to save in one csv file!

Nice idea! I'll try it.

**Comment by Tps-F** [comment]
Done!
[0210b3b](https://github.com/Tps-F/sd-webui-blip2/commit/0210b3bd636a9941852d2536aa3ff7e9d6c95495)

**Comment by oaefou** [comment]
Thx Bro !

There is also a cool feature.
Caption min length
Caption max length

https://github.com/p1atdev/stable-diffusion-webui-blip2-captioner/blob/main/screenshots/screenshot-1.jpg
